config/routes.rb
Rails.application.routes.draw do
  put "/carts/update/", to: "carts#update"
  devise_scope :user do
    get "/login", to: "devise/sessions#new"
    delete "/logout", to: "devise/sessions#destroy"
    post "/sign_up", to: "devise/registrations#create"
  end
  devise_for :users
  root "static_pages#home"
  resources :orders, only: %i(index destroy create) do
    resources :order_details, only: :index
  end
  resource :cart, except: %i(index new edit)
  resources :products, only: %i(show index)
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/category.rb
class Category < ApplicationRecord
  has_many :products, dependent: :destroy
  has_many :suggests, dependent: :destroy
end

app/models/order.rb
class Order < ApplicationRecord
  belongs_to :user
  has_many :order_details, dependent: :destroy
end

app/models/order_detail.rb
class OrderDetail < ApplicationRecord
  belongs_to :order
  belongs_to :product
  delegate :name, to: :product, prefix: :product, allow_nil: true
  delegate :price, to: :product, prefix: :product, allow_nil: true
  delegate :picture, to: :product, prefix: :product, allow_nil: true
  delegate :quantity, to: :product, prefix: :product, allow_nil: true
end

app/models/product.rb
class Product < ApplicationRecord
  belongs_to :category
  has_many :product_pictures, dependent: :destroy
  has_many :order_details, dependent: :destroy
  has_many :ratings, dependent: :destroy
  mount_uploader :picture, PictureUploader
  scope :filter_by_category, ->(category_id){where(category_id: category_id) if category_id.present?}
end

app/models/product_picture.rb
class ProductPicture < ApplicationRecord
  belongs_to :product
end

app/models/rating.rb
class Rating < ApplicationRecord
  belongs_to :product
  belongs_to :user
end

app/models/suggest.rb
class Suggest < ApplicationRecord
  belongs_to :user
  belongs_to :category
end

app/models/user.rb
class User < ApplicationRecord
  has_many :orders, dependent: :destroy
  has_many :ratings, dependent: :destroy
  has_many :suggests, dependent: :destroy
  devise :database_authenticatable, :registerable, :recoverable, :rememberable,
    :trackable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  helper_method :current_order

  def current_order
    session[:cart] ||= []
  end
end

app/controllers/carts_controller.rb
class CartsController < ApplicationController
  before_action :load_product, only: %i(create update)
  before_action :current_order, only: :show
  before_action :load_cart, only: %i(show update)

  def show; end

  def create
    order_detail = OrderDetail.new cart_params
    result = find_product_in_cart order_detail.product_id
    check_cart order_detail, result
    redirect_to cart_path
  end

  def update
    quantity = params[:quantity].to_i
    respond_to do |format|
      format.html{redirect_to cart_path}
      format.js
      if quantity > @product.quantity || quantity <= 0
        format.json{render json: {quantity_product: @product.quantity, message: t(".invalid_quantity")}}
      else
        result = find_product_in_cart(@product.id)
        result["quantity"] = quantity
        format.json{render json: {result: result, product: @product, order_details: @order_details}.to_json}
      end
    end
  end

  private

  def cart_params
    params.permit :product_id, :quantity, :price
  end

  def load_product
    current_order
    @product = Product.find_by id: params[:product_id]
    return if @product
    flash[:danger] = t "products.not_found_product"
    redirect_to root_path
  end

  def find_product_in_cart product_id
    session[:cart].find do |item|
      item if item["product_id"] == product_id
    end
  end

  def check_quantity result, quantity
    if result["quantity"] + quantity > @product.quantity
      flash[:danger] = t ".invalid_quantity"
    else
      result["quantity"] += quantity
    end
  end

  def check_cart order_detail, result
    if order_detail.quantity.nil? || order_detail.quantity <= 0
      flash[:danger] = t ".fail_add_cart"
    elsif result
      check_quantity result, order_detail.quantity
    else
      session[:cart] << order_detail
      flash[:success] = t ".success_add_cart"
    end
  end

  def load_cart
    @order_details = []
    session[:cart].each do |item|
      @order_details << OrderDetail.new(item)
    end
  end
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  before_action :load_product, only: :show

  def show; end

  private

  def load_product
    @product = Product.find_by id: params[:id]
    return if @product
    flash[:danger] = t ".not_found_product"
    redirect_to root_url
  end
end

app/controllers/sessions_controller.rb
class SessionsController < Devise::SessionsController
  def new
    pre_login_url
    super
  end

  def create
    @referer_url = root_path
    super
  end

  def destroy
    @referer_url = root_path
    super
  end

  private

  def pre_login_url
    @referer_url = root_path
  end

  def after_sign_in_path_for resource
    sign_in_url = url_for(action: "new", controller: "sessions", only_path: false, protocol: "http")
    if @referer_url == sign_in_url
      super
    else
      @referer_url || root_path
    end
  end
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def home
    @products = Product.page(params[:page]).per(Settings.home.per_home)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authenticate_user!
end

app/helpers/application_helper.rb
module ApplicationHelper
  def full_title page_title
    base_title = I18n.t "base_title"
    if page_title.blank?
      base_title
    else
      page_title + " | " + base_title
    end
  end
end

app/helpers/carts_helper.rb
module CartsHelper
  def amount unit_price, quantity
    unit_price * quantity
  end

  def total_price order_details
    total = 0
    order_details.each do |item|
      total += amount item.product_price, item.quantity
    end
    total
  end
end

app/views/carts/_order_cart.html.erb
<tr>
  <td class="invert-closeb">
    <%= link_to cart_path(product_id: order_detail.product_id), method: :delete,
    data: {confirm: t("carts.confirm")} do %>
      <div class="rem">
        <div class="close1"></div>
      </div>
    <% end %>
  </td>
  <td class="invert-image">
    <%= link_to order_detail.product do %>
      <%= image_tag order_detail.product_picture.url %>
    <% end %>
  </td>
  <td class="invert">
    <%= link_to order_detail.product do %>
      <%= order_detail.product_name %>
    <% end %>
  </td>
  <td class="invert"><%= order_detail.product_price %></td>
  <%= form_tag cart_path(product_id: order_detail.product_id), method: :patch, remote: true do %>
  <td class="invert">
    <div class="quantity">
      <%= number_field_tag :quantity, nil, class: "form-control input-sm quantity_#{order_detail.product_id}", min: Settings.products.min_quantity,
          max: order_detail.product_quantity,
            value: order_detail.quantity, onChange: "OnChangeQuantity(#{order_detail.product_id})" %>
      <br />
      <%= hidden_field_tag "product_id", order_detail.product_id, class: "product_id" %>
    </div>
  </td>
  <td class="invert total_<%= order_detail.product_id %>"><%= t("product_price", price: amount(order_detail.product_price, order_detail.quantity)) %></td>
  <% end %>
</tr>

app/views/carts/_shop_cart.html.erb
<table class="timetable_sub">
  <thead>
    <tr>
      <th><%= t ".remove" %></th>
      <th><%= t ".product" %></th>
      <th><%= t ".name" %></th>
      <th><%= t ".price" %></th>
      <th><%= t ".quantity" %></th>
      <th><%= t ".amount" %></th>
    </tr>
  </thead>
  <%= render partial: "order_cart", collection: @order_details, as: :order_detail %>
  <tr>
    <th><%= t ".total" %></th>
    <td class="total_price"><%= t("product_price", price: total_price(@order_details)) %></td>
  </tr>
</table>

app/views/carts/show.html.erb
<% provide :title, t("carts.title") %>
<div class="checkout">
  <div class="container">
    <h3><%= t ".my_shopping" %></h3>
    <div class="table-responsive checkout-right animated wow slideInUp" data-wow-delay=".5s">
      <%= render "shop_cart" %>
    </div>
  </div>
</div>

app/views/layouts/_banner.html.erb
<div class="ban-top">
  <div class="container">
    <div class="top_nav_left">
      <nav class="navbar navbar-default">
        <div class="container-fluid">
          <div class="navbar-header">
            <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
            <span class="sr-only"><%= t ".toggle" %></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            </button>
          </div>
          <div class="collapse navbar-collapse menu--shylock" id="bs-example-navbar-collapse-1">
            <ul class="nav navbar-nav menu__list">
              <li class="active menu__item menu__item--current">
                <%= link_to root_url, class: "menu__link" do %>
                  <%= t ".home" %>
                  <span class="sr-only">(current)</span>
                <% end %>
              </li>
              <li class=" menu__item">
                <%= link_to t(".foods"), root_url, class: "menu__link"%>
              </li>
              <li class="menu__item">
                <%= link_to t(".drinks"), root_url, class: "menu__link"%>
              </li>
              <li class="menu__item">
                <%= link_to t(".contact"), root_url, class: "menu__link"%>
              </li>
              <li class="menu__item">
                <%= link_to t(".signup"), new_user_registration_path, class: "menu__link"%>
              </li>
            </ul>
          </div>
        </div>
      </nav>
    </div>
    <div class="top_nav_right">
      <div class="cart box_1">
        <a href="checkout.html">
          <h3>
            <div class="total">
              <i class="glyphicon glyphicon-shopping-cart" aria-hidden="true"></i>
              <span class="simpleCart_total"></span> (<span id="simpleCart_quantity" class="simpleCart_quantity"></span><%= t ".items" %>)
            </div>
          </h3>
        </a>
        <p><a href="javascript:;" class="simpleCart_empty"><%= t ".empty_cart" %></a></p>
      </div>
    </div>
    <div class="clearfix"></div>
  </div>
</div>

app/views/layouts/_flash.html.erb
<% flash.each do |message_type, message| %>
  <div class="alert alert-<%= message_type %>"><%= message %></div>
<% end %>

app/views/layouts/_footer.html.erb
<div class="footer">
  <div class="container">
    <div class="clearfix"></div>
    <p class="copy-right"><%= t ".copy_right" %>
      <a href="http://w3layouts.com/"><%= t ".w3layouts" %></a>
    </p>
  </div>
</div>

app/views/layouts/_header.html.erb
<div class="header">
  <div class="container">
    <ul>
      <li>
        <span class="glyphicon glyphicon-time" aria-hidden="true"></span>
        <%= t ".free_and_fast" %>
      </li>
      <li>
        <span class="glyphicon glyphicon-shopping-cart" aria-hidden="true"></span>
        <%= t ".free_ship" %>
      </li>
      <li>
        <span class="glyphicon glyphicon-envelope" aria-hidden="true"></span>
        <a href="mailto:info@example.com"><%= t ".mail_to" %></a>
      </li>
    </ul>
  </div>
</div>
<div class="header-bot">
  <div class="container">
    <div class="col-md-3 header-left">
    </div>
    <div class="col-md-6 header-middle">
      <form>
        <div class="search">
          <input type="search" value="Search">
        </div>
        <div class="section_room">
          <select id="country" onchange="change_country(this.value)" class="frm-field required">
            <option value="null"><%= t ".all_cate" %></option>
          </select>
        </div>
        <div class="sear-sub">
          <input type="submit" value=" ">
        </div>
        <div class="clearfix"></div>
      </form>
    </div>
    <div class="col-md-3 header-right footer-bottom">
      <ul>
        <% if user_signed_in?%>
          <li>
            <%= link_to logout_path, class: "use1", method: :delete do %>
              <span><%= t ".logout" %></span>
            <% end %>
          </li>
        <% else %>
          <li>
            <%= link_to login_path, class: "use1" do %>
              <span><%= t ".login" %></span>
            <% end %>
          </li>
        <% end %>
        <li><a class="fb" href="#"></a></li>
        <li><a class="twi" href="#"></a></li>
        <li><a class="insta" href="#"></a></li>
        <li><a class="you" href="#"></a></li>
      </ul>
    </div>
    <div class="clearfix"></div>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= full_title(yield :title) %></title>
    <%= csrf_meta_tags %>
    <%= stylesheet_link_tag "application", media: "all", "data-turbolinks-track": "reload" %>
    <%= javascript_include_tag "application", "data-turbolinks-track": "reload" %>
  </head>
  <body>
    <%= render "layouts/header" %>
    <%= render "layouts/banner" %>
    <div class="container">
      <%= render "layouts/flash" %>
    </div>
    <%= yield %>
    <%= render "layouts/footer" %>
    <%= debug params if Rails.env.development? %>
  </body>
</html>

app/views/products/show.html.erb
<div class="single">
  <div class="container">
    <div class="col-md-6 single-right-left animated wow slideInUp animated" >
      <div class="grid images_3_of_2">
        <%= image_tag @product.picture.url, class: "thumbnail" %>
      </div>
    </div>
    <div class="col-md-6 single-right-left simpleCart_shelfItem animated wow slideInRight animated">
      <%= form_tag cart_path(product_id: @product.id), method: :post do %>
        <h3><%= @product.name %></h3>
        <p><span class="item_price"><%= t("product_price", price: @product.price ) %></span></p>
        <div class="color-quality">
          <div class="color-quality-right">
            <h5><%= t ".quantity" %></h5>
            <%= number_field_tag :quantity, nil,
              value: Settings.products.min_quantity, min: Settings.products.min_quantity,
              max: @product.quantity, required: true %>
            <%= hidden_field_tag "price", @product.price, class: "product_id" %>
          </div>
        </div>
        <div class="occasional">
          <h5><%= t ".types" %></h5>
          <div class="colr ert">
            <label class="radio">
              <input type="radio" name="radio" checked=""><i></i><%= @product.category.name %>
            </label>
          </div>
          <div class="clearfix"></div>
        </div>
        <div class="occasion-cart">
          <%= button_tag type: "submit", class: "item_add hvr-outline-out button2",
              title: t(".add_cart"), name: nil do %>
            <%= t(".add_cart") %>
          <% end %>
        </div>
      <% end %>
    </div>
    <div class="clearfix"></div>
    <div class="bootstrap-tab animated wow slideInUp animated">
      <div class="bs-example bs-example-tabs" role="tabpanel" data-example-id="togglable-tabs">
        <ul id="myTab" class="nav nav-tabs" role="tablist">
          <li role="presentation" class="active">
            <a href="#home" id="home-tab" role="tab" data-toggle="tab" aria-controls="home" aria-expanded="true">
              <%= t "description" %>
            </a>
          </li>
        </ul>
        <div id="myTabContent" class="tab-content">
          <div role="tabpanel" class="tab-pane fade in active bootstrap-tab-text" id="home" aria-labelledby="home-tab">
            <%= @product.detail %>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/static_pages/_product.html.erb
<div class="col-md-3 product-men">
  <div class="men-pro-item simpleCart_shelfItem">
    <div class="men-thumb-item">
      <%= image_tag product.picture.url, class: "thumbnail" %>
      <div class="men-cart-pro">
        <div class="inner-men-cart-pro">
          <%= link_to t(".quickview"), product_path(product), class: "link-product-add-cart" %>
        </div>
      </div>
    </div>
    <div class="item-info-product ">
      <h4><a href="single.html"><%= product.name %></a></h4>
      <div class="info-product-price">
        <span class="item_price"><%= product.price %></span>
      </div>
      <%= link_to t(".add_cart"), "#", class: "item_add single-item hvr-outline-out button2" %>
    </div>
  </div>
</div>

app/views/static_pages/home.html.erb
<div class="product-easy">
  <div class="container">
    <%= render partial: "product", collection: @products  %>
    <div class="clearfix"></div>
    <%= paginate @products %>
  </div>
</div>